config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    confirmations: "users/confirmations"
  }

  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  root "pages#show", page: "home"
  get "password_resets/new"
  get "password_resets/edit"
  get "pages/:page" => "pages#show"

  resources :users
  resources :doctors
  resources :account_activations, only: [:edit]
  resource :likes, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :questions, concerns: :paginatable
  resources :answers, only: [:index, :create, :destroy]
  resources :comments, only: [:create, :edit, :destroy, :update]
  resources :searchs, only: [:index, :show]
  resources :diseases, only: [:index, :show]
  resources :medicine_classes, only: [:index]
  resources :medicine_types, only: [:show]
  resources :medicines, only: [:show]
  resources :notifications, only: [:update] do
    post :mark_all_as_checked, on: :collection
  end
  resources :bookings, only: [:create, :update, :destroy]
  resources :schedules, only: [:index]

  resources :conversations do
    member do
      post :close
    end
    resources :messages
  end

  namespace :admin do
    get "/", to: "dashboards#index"
    resources :doctors
    resources :users, only: [:index, :update]
    resources :questions, only: [:index, :destroy]
    resources :answers, only: [:index, :destroy]
    resource :block_users, only: [:create, :destroy]
    resource :activate_doctors, only: [:create]
  end

  mount ActionCable.server => "/cable"
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User.name
  belongs_to :receiver, foreign_key: :receiver_id, class_name: User.name

  validates :sender_id, uniqueness: {scope: :receiver_id}

  scope :between, lambda do |s_id, r_id|
    where(sender_id: s_id, receiver_id: r_id).or(
      where(sender_id: r_id, receiver_id: s_id)
    )
  end

  def self.get s_id, r_id
    conversation = between(s_id, r_id).first
    return conversation if conversation.present?
    create(sender_id: s_id, receiver_id: r_id)
  end

  def opposed_user user
    user == receiver ? sender : receiver
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def create
    @conversation = Conversation.get params[:conversation][:sender_id],
      params[:conversation][:receiver_id]
    add_to_conversations unless conversated?
  end

  def destroy; end

  def close
    @conversation = Conversation.find(params[:id])
    session[:conversations].delete(@conversation.id)
  end

  private

  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end

  def conversated?
    session[:conversations]&.include? @conversation.id
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def load_current_conversations
    return if session[:conversations].nil?
    @conversations = Conversation.includes(:receiver, :messages)
                                 .find_by id: session[:conversations]
  end
end

app/views/conversations/_conversation.html.erb
<div class="chat_frame conversation-<%= conversation.id %>"
  data-conversation-id="<%= conversation.id %>">
  <div class="chat_header">
    <%= link_to conversation.opposed_user(user).name,
      conversation.opposed_user(user) %>
    <%= link_to close_conversation_path(conversation),
      class: "chat-close-icon", remote: true, method: :post do %>
      <i class=" icon-cancel-circled-1"></i>
    <% end %>
  </div>
  <div class="chat_content chat_content-<%= conversation.id %>">
    <div class="chat_timeline--view">
      <% conversation.messages.each do |mess| %>
        <%= render "messages/message", message: mess %>
      <% end %>
    </div>
    <div class="chat_form">
      <%= form_for [conversation, conversation.messages.build],
        html:{class:"form-group massges_form"}, remote: true do |f| %>
        <%= f.hidden_field :user_id, value: user.id %>
        <%= f.text_area :content, rows: 1,
          placeholder: "Nhập để gửi tin...",
          class: "form-control input_message_content" %>
        <%= f.button :submit, class: "sent_btn" do %>
        <i class="icon-right-circled"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/conversations/close.js.erb
var conversationId = '<%= @conversation.id %>';
var chatFrame = $('.chat_frame.conversation-'+conversationId);
chatFrame.remove()

app/views/conversations/create.js.erb
var conversationId = '<%= @conversation.id %>';
var chatFrame = $('.chat_frame.conversation-'+conversationId);

if(chatFrame.length <= 0){
  $('.mf_conversation--frame')
    .append('<%= j render "conversations/conversation",
  conversation: @conversation, user: current_user %>');
  var chatHeader = $('.chat_frame.conversation-' + conversationId
    + ' .chat_header');
  initConversationEvent(chatHeader);
}

showChatContent(conversationId)