config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    confirmations: "users/confirmations"
  }

  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  root "pages#show", page: "home"
  get "password_resets/new"
  get "password_resets/edit"
  get "pages/:page" => "pages#show"

  resources :users
  resources :doctors
  resources :account_activations, only: [:edit]
  resource :likes, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :questions, concerns: :paginatable
  resources :answers, only: [:index, :create, :destroy]
  resources :comments, only: [:create, :edit, :destroy, :update]
  resources :searchs, only: [:index, :show]
  resources :diseases, only: [:index, :show]
  resources :medicine_classes, only: [:index]
  resources :medicine_types, only: [:show]
  resources :medicines, only: [:show]
  resources :notifications, only: [:update] do
    post :mark_all_as_checked, on: :collection
  end
  resources :bookings, only: [:create, :update, :destroy]
  resources :schedules, only: [:index]

  resources :conversations do
    member do
      post :close
    end
    resources :messages
  end

  namespace :admin do
    get "/", to: "dashboards#index"
    resources :doctors
    resources :users, only: [:index, :update]
    resources :questions, only: [:index, :destroy]
    resources :answers, only: [:index, :destroy]
    resource :block_users, only: [:create, :destroy]
    resource :activate_doctors, only: [:create]
  end

  mount ActionCable.server => "/cable"
end

app/views/layouts/admin/_footer.html.erb
<footer class="main-footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6">
        <p><%= "#{t 'global.logo'} - #{Time.current.year}" %></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/admin/_head.html.erb
<head>
  <title><%= full_title yield :title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "vendors", media: "all",
    "data-turbolinks-track": "reload" %>
  <%= stylesheet_link_tag "admin/admin", media: "all",
    "data-turbolinks-track": "reload" %>
  <%= javascript_include_tag "admin/admin", "data-turbolinks-track": "reload" %>
  <%= render "layouts/shim" %>
</head>

app/views/layouts/admin/_header.html.erb
<header class="header">
  <nav class="navbar">
    <div class="container-fluid">
      <div class="navbar-holder d-flex align-items-center justify-content-between">
        <div class="navbar-header">
          <%= link_to "#", class: "menu-btn", id: "toggle-btn" do %>
            <i class="fa fa-bars"></i>
          <% end %>
          <%= link_to "#", class: "navbar-brand" do %>
            <div class="brand-text d-none d-md-inline-block">
              <strong class="text-primary"><%= t "global.logo" %></strong>
            </div>
          <% end %>
        </div>
        <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete,
              class: "nav-link logout" do %>
              <span class="d-none d-sm-inline-block">
                <%= t "admin.common.logout" %>
              </span>
              <i class="fa fa-sign-out"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/admin/_navbar.html.erb
<nav class="side-navbar">
  <div class="side-navbar-wrapper">
    <div class="sidenav-header d-flex align-items-center justify-content-center">
      <div class="sidenav-header-inner text-center">
        <%= image_tag "logo.png" %>
        <h2 class="h5"><%= current_user.name %></h2>
        <span><%= t "admin.title" %></span>
      </div>
      <div class="sidenav-header-logo">
        <%= link_to root_url, class: "brand-small text-center" do %>
          <strong>M</strong><strong class="text-primary">F</strong>
        <% end %>
      </div>
    </div>
    <div class="main-menu">
      <h5 class="sidenav-heading"><%= t "admin.main" %></h5>
      <ul id="side-main-menu" class="side-menu list-unstyled">
        <li>
          <%= link_to admin_doctors_path do %>
            <i class="fa fa-user-md"></i><%= t "admin.doctors.title" %>
          <% end %>
        </li>
        <li>
          <%= link_to admin_users_path do %>
            <i class="fa fa-users"></i><%= t "admin.users.title" %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-question-circle"></i>
            <%= t "admin.questions.title" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin/index.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/admin/head" %>
  <body>
    <%= render "layouts/admin/navbar" %>
    <div class="page">
      <%= render "layouts/admin/header" %>
      <section class="section-padding">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </section>
      <%= render "layouts/admin/footer" %>
    </div>
  </body>
</html>