config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    confirmations: "users/confirmations"
  }

  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  root "pages#show", page: "home"
  get "password_resets/new"
  get "password_resets/edit"
  get "pages/:page" => "pages#show"

  resources :users
  resources :doctors
  resources :account_activations, only: [:edit]
  resource :likes, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :questions, concerns: :paginatable
  resources :answers, only: [:index, :create, :destroy]
  resources :comments, only: [:create, :edit, :destroy, :update]
  resources :searchs, only: [:index, :show]
  resources :diseases, only: [:index, :show]
  resources :medicine_classes, only: [:index]
  resources :medicine_types, only: [:show]
  resources :medicines, only: [:show]
  resources :notifications, only: [:update] do
    post :mark_all_as_checked, on: :collection
  end
  resources :bookings, only: [:create, :update, :destroy]
  resources :schedules, only: [:index]

  resources :conversations do
    member do
      post :close
    end
    resources :messages
  end

  namespace :admin do
    get "/", to: "dashboards#index"
    resources :doctors
    resources :users, only: [:index, :update]
    resources :questions, only: [:index, :destroy]
    resources :answers, only: [:index, :destroy]
    resource :block_users, only: [:create, :destroy]
    resource :activate_doctors, only: [:create]
  end

  mount ActionCable.server => "/cable"
end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
  def index
    @diseases = Disease.exclude_content.name_asc.group_by do |item|
      item.name.parameterize.upcase[0]
    end
    @diseases = @diseases.to_a
  end

  def show
    @disease = Disease.friendly.find_by slug: params[:id]
    return if @disease
    flash[:message] = t "error.page_not_found"
    render "shared/404"
  end
end

app/views/diseases/index.html.erb
<% provide :title, t(".title") %>
<main>
  <div id="disease-list" class="container">
    <% @diseases.each do |key, array| %>
      <div class="row">
        <h3><%= key %></h3>
        <ul>
          <% array.each do |disease| %>
            <li>
              <%= link_to disease_path(disease) do %>
                <i class="icon-chart"></i>
                <%= disease.name %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div id="toTop" class="to-top"></div>
</main>

app/views/diseases/show.html.erb
<% provide :title, @disease.name %>
<main>
  <div id="disease-detail" class="container margin_60">
    <div class="row">
      <div class="col-xl-8 col-md-8">
        <nav id="secondary_nav">
          <div class="container">
            <ul class="clearfix">
              <li class="active active-title"><%= @disease.name %></li>
            </ul>
          </div>
        </nav>
        <div class="box_general_3">
          <div><%= @disease.content_html.html_safe %></div>
        </div>
      </div>
      <div class="col-xl-4 col-md-4">
        <div class="box_general_3 booking">
          <div class="title"><%= t ".doctor" %></div>
          <ul class="">
            <% @disease.category.doctors.each do |doctor| %>
              <li>
                <div class="strip_list">
                  <figure>
                    <%= link_to doctor_path(doctor) do %>
                      <%= image_tag user_avatar(doctor) %>
                    <% end %>
                  </figure>
                  <p>
                    <%= link_to t(".doctor_name", name: doctor.name),
                      doctor_path(doctor) %>
                  </p>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</main>